### ISSUE TITLE
Dependancy issue with pulsar4s and pulsar-functions-local-runner-original/pulsar-client-admin-original

### ISSUE THREAD

**Issue by Haaroon** [CleverCloud/pulsar4s#371]
Having issues whereby my Local File Reader runner fails to run because of a dependency clash between pulsar4s and the pulsar java libraries. 

The code is attempting to load a connector via the soureConfig object 

Below is the build.sbt file, 

```
libraryDependencies += "com.sksamuel.pulsar4s"        %% "pulsar4s-core"                   % "2.7.3"
libraryDependencies += "com.sksamuel.pulsar4s"        %% "pulsar4s-circe"                  % "2.7.3"
libraryDependencies += "org.apache.pulsar"            %  "pulsar-client-messagecrypto-bc"  % pulsarVersion
libraryDependencies += "org.apache.pulsar"            %  "pulsar-functions-local-runner-original" % pulsarVersion
libraryDependencies += "org.apache.pulsar"            %  "pulsar-client-admin-original"    % pulsarVersion
```

Below is the error log 
```
15:19:03.712 [main] INFO  org.apache.pulsar.functions.utils.io.ConnectorUtils - Searching for connectors in /Users/haaroony/Documents/pulsar/pulsar-test/connectors
15:19:03.773 [main] WARN  org.apache.pulsar.functions.utils.io.ConnectorUtils - Failed to load connector from /Users/haaroony/Documents/pulsar/pulsar-test/connectors/pulsar-io-file-2.7.2.nar
java.lang.NoSuchMethodError: 'com.fasterxml.jackson.databind.ObjectMapper org.apache.pulsar.common.util.ObjectMapperFactory.getThreadLocalYaml()'
	at org.apache.pulsar.functions.utils.io.ConnectorUtils.getConnectorDefinition(ConnectorUtils.java:115) ~[pulsar-functions-utils-2.7.2.jar:2.7.2]
	at org.apache.pulsar.functions.utils.io.ConnectorUtils.getConnectorDefinition(ConnectorUtils.java:107) ~[pulsar-functions-utils-2.7.2.jar:2.7.2]
	at org.apache.pulsar.functions.utils.io.ConnectorUtils.searchForConnectors(ConnectorUtils.java:164) [pulsar-functions-utils-2.7.2.jar:2.7.2]
	at org.apache.pulsar.functions.LocalRunner.getConnectors(LocalRunner.java:508) [pulsar-functions-local-runner-original-2.7.2.jar:2.7.2]
	at org.apache.pulsar.functions.LocalRunner.isBuiltInSource(LocalRunner.java:477) [pulsar-functions-local-runner-original-2.7.2.jar:2.7.2]
	at org.apache.pulsar.functions.LocalRunner.start(LocalRunner.java:275) [pulsar-functions-local-runner-original-2.7.2.jar:2.7.2]
	at com.raphtory.FileSpoutLocal$.main(FileSpoutLocal.scala:32) [classes/:?]
	at com.raphtory.FileSpoutLocal.main(FileSpoutLocal.scala) [classes/:?]
Exception in thread "main" java.lang.NoSuchMethodError: 'com.fasterxml.jackson.databind.ObjectMapper org.apache.pulsar.common.util.ObjectMapperFactory.getThreadLocalYaml()'
	at org.apache.pulsar.functions.utils.io.ConnectorUtils.getIOSourceClass(ConnectorUtils.java:59)
	at org.apache.pulsar.functions.utils.SourceConfigUtils.validate(SourceConfigUtils.java:303)
	at org.apache.pulsar.functions.LocalRunner.start(LocalRunner.java:290)
	at com.raphtory.FileSpoutLocal$.main(FileSpoutLocal.scala:32)
	at com.raphtory.FileSpoutLocal.main(FileSpoutLocal.scala)
15:19:03.893 [Thread-0] INFO  org.apache.pulsar.functions.LocalRunner - Shutting down the localrun runtimeSpawner ...
```
code example
```
      val sourceConfig = SourceConfig.builder
        .tenant("public")
        .namespace("default")
        .topicName("example-file-io")
        .name("file-source-example")
        .archive("/Users/haaroony/Documents/pulsar/pulsar-test/connectors/pulsar-io-file-2.7.2.nar")
        .configs(configs)
        .build

      val localRunner = LocalRunner.builder
        .brokerServiceUrl("pulsar://localhost:6650")
        .sourceConfig(sourceConfig)
        .build

      localRunner.start(false)
```

**Comment by Haaroon** [comment]
fyi if i remove pulsar4s it runs fine

**Comment by judu** [comment]
Does this fail for every pulsar java client version? Which version are you on?

**Comment by Haaroon** [comment]
Running the latest 2.8.0 with pulsar 2.9.0, i even tried pulsar 2.8.1 and same issues

**Comment by judu** [comment]
Out of curiosity: did you try pulsar4s 2.8.0?
It's been released yesterday.
Beware: since the original maintainer gave the project away, the organisation for the artifact is now `com.clever-cloud.pulsar4s` instead of `com.sksamuel.pulsar4s`.

**Comment by Haaroon** [comment]
yes i did and it still doesnt work unfortunately,

**Comment by Haaroon** [comment]
I have had a similar dependency issue with pulsar before, which is why we add the `-original` name to the dep which pull the build without the shady deps

**Comment by miratepuffin** [comment]
![image](https://user-images.githubusercontent.com/6665739/145446250-cfc0293a-c087-4b54-8a27-fba0ea71a110.png)
I don't think this is a solution solution, but as a quick patch to get this working I excluded the base pulsar libs from pulsar4s in my build and it now runs (I work with Haaroon).

**Comment by judu** [comment]
That *is* weird, because pulsar4s 2.8.0 depends on pulsar-client 2.9.0. :thinking:

**Comment by Haaroon** [comment]
It is indeed. I believe client has dependency issues which is why use client-common instead. It gives problems with pulsar functions .

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by judu** [comment]
I may investigate this in future versions. If possible, drop the `pulsar-client` to use the other ones, or add the others with versions pinning.

**Comment by judu** [comment]
Would you agree to run some tests in local by cloning this repo, mangling the deps to your liking, see if your project works with it and see if the tests still pass? :pray:

**Comment by miratepuffin** [comment]
Sure, can do. We are getting a wonderful netty issue as well at the moment (below) which also seems to be a dependency problem, so this could help with that.
![image](https://user-images.githubusercontent.com/6665739/145563215-af5791fa-0758-4154-ab9b-d5933568f551.png)

**Comment by judu** [comment]
Oh, the much dreaded netty error. Some coworkers got it but we could not find out why. :(

**Comment by Haaroon** [comment]
we have the netty but it seems to work all fine
